"""empty message

Revision ID: 3f07f1635aa7
Revises: e9593c42deae
Create Date: 2022-02-18 21:20:57.588872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f07f1635aa7'
down_revision = 'e9593c42deae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('arrive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'arrive')
    # ### end Alembic commands ###
