"""empty message

Revision ID: e9593c42deae
Revises: 64520eac3d27
Create Date: 2022-02-18 16:52:33.935489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9593c42deae'
down_revision = '64520eac3d27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('merchant_take_order', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'merchant_take_order')
    # ### end Alembic commands ###
